rosrun dynamic_reconfigure dynparam load /move_base p3at_move_base_rqt_configure.yaml
rosrun dynamic_reconfigure dynparam load /move_base/TebLocalPlannerROS p3at_move_base_teb_rqt_configure.yaml
rosrun dynamic_reconfigure dynparam load /move_base/global_costmap p3at_move_base_gcostmap_rqt_configure.yaml
rosrun dynamic_reconfigure dynparam load /move_base/local_costmap p3at_move_base_lcostmap_rqt_configure.yaml

