!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  footprint: '[[0.3302,-0.0508],[0.254,-0.0508],[0.254,-0.254],[-0.254,-0.254],[-0.254,0.254],[0.254,0.254],[0.254,0.0508],[0.3302,0.0508]]'
  footprint_padding: 0.01
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      footprint: '[[0.3302,-0.0508],[0.254,-0.0508],[0.254,-0.254],[-0.254,-0.254],[-0.254,0.254],[0.254,0.254],[0.254,0.0508],[0.3302,0.0508]]'
      footprint_padding: 0.01
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      height: 3
      id: 0
      name: Default
      origin_x: 0.0
      origin_y: 0.0
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      publish_frequency: 10.0
      resolution: 0.05
      robot_radius: 0.46
      state: true
      transform_tolerance: 0.3
      type: ''
      update_frequency: 3.0
      width: 3
    state: []
  height: 3
  origin_x: 0.0
  origin_y: 0.0
  publish_frequency: 10.0
  resolution: 0.05
  robot_radius: 0.46
  transform_tolerance: 0.3
  update_frequency: 3.0
  width: 3
state: []
